services:
  - type: web
    name: whisper_audio_text_v1
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
    startCommand: python app.py
